server:
  port: 9000
  
spring:
  cloud:
    gateway:
      routes:
        - id: microservice1
          uri: lb://microservice1
          predicates:
            - Path= /catalog/message, /catalog/message/{userId}
#      discovery:
#        locator:
#          enabled: true
#          lowerCaseServiceId: true

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka    

   