resilience4j.retry:
    instances:
      userService:
        maxRetryAttempts: 5     #will do 4 retry attempts, maxAttempts attribute also working
        waitDuration: 5s
        retryExceptions:
          - java.lang.Exception